### PR TITLE
docs: Possible idea to include underlying TypeScript types into the API Documentation

### LINKED ISSUE #47: Include underlying TypeScript types into the API Documentation
The current [API Documentation](https://github.com/asyncapi/diff/blob/master/API.md), which is generated automatically using `jsdoc2md`, doesn't include the underlying types.
For example,
image

It is not clear what the `DiffOutputItem` "looks" like.

**The reason:**

JSDoc2md does not include TypeScript types when it looks into JSDoc comments, or rather, It doesn't find the typescript types when generating the documentation.

**Request:**

We want the underlying TypeScript types to be present inside the auto-generated API documentation. 

The output will depend on how `jsdoc2md` parses the types. One can look into `jsdoc2md` documentation to see how to parse the TypeScript types :)

### PR DESCRIPTION
**Pull request by ron-debajyoti**
**Description**

- uses the plugin `jsdoc-tsimport-plugin` to properly parse jsdoc comments with import tags

**Related issue(s)**
Partially fixes #47

### CODE REVIEW

**Comment by aayushmau5** [comment]
@ron-debajyoti Hey, just wanted to check in. Did you have any luck with fixing the problem?

**Comment by ron-debajyoti** [comment]
> @ron-debajyoti Hey, just wanted to check in. Did you have any luck with fixing the problem?

Oh damn, I kinda forgot about this. How bout I check it out again for the next 2-3 hours. I feel the last time I had some progress just need to revisit it again.

**Comment by aayushmau5** [comment]
Sure, take your time :)

**Comment by ron-debajyoti** [comment]
> Sure, take your time :)

Hey @aayushmau5 , I'm closing this draft PR and opening a new PR, since this is on the master branch. Perhaps we could shift the discussion there.

**Pull request closed without merging**
