### PR TITLE
feat: add spec v3 support

### PR DESCRIPTION
**Pull request by aayushmau5**
**Description**

Add support for AsyncAPI v3

**Related issue(s)**
https://github.com/asyncapi/diff/issues/154

### CODE REVIEW

**Comment by aayushmau5** [comment]
@jonaslagoni @derberg here's a PR for spec v3 support in diff. It's a draft PR(right now there's no tests, and docs, etc). Please review the approach and the code changes I have made here. 

One question:

As discussed in the meeting I had with Jonas, we aren't going to compare v2 against v3. I'm not sure what type of error do we show here? An early return? Keep in mind that this will be used by CLI, so we need to have it so that CLI is able to show the error as well.

**Comment by derberg** [comment]
sorry for late response.

so basically the diff tool purpose is to help people with review of changes that they are doing in their documents to identify breaking changes or new topics, or other things. So yeah, I think you should disallow comparing files between versions and throw error that it is technically not possible and why. Does that help?

**Comment by aeworxet** [comment]
@asyncapi/bounty_team

**Review by derberg — COMMENTED** [review]
- for sonar cloud, just ignore: https://github.com/asyncapi/diff/blob/master/.sonarcloud.properties
- I suggest you also remove in this PR `@vinitshahdeo @onbit-uchenik` from `CODEOWNERS` as they anyway never contributed after creation of this project

**Review by derberg — APPROVED** [review]

**Comment by derberg** [comment]
@aayushmau5 that's working out of the box with CLI right? no additional flags enablement or stuff like that?

**Comment by derberg** [comment]
if all good them please hit `rtm` comment in https://github.com/asyncapi/cli/pull/1595

**Pull request merged**
